const medicines = [
  {
    title: "Tefi-O 200 DT tab",
    description: "Cefixime Dispersible Tab IP 200 mg",
    brand: "Tefi-O",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab", // Dummy
    mrp: 109,
    inStockNumber: 10, // Dummy
    isAvailable: true, // Dummy
    image: {
      public_id: "dummy_public_id_tefi-o-200-dt",
      url: "https://via.placeholder.com/150?text=Tefi-O+200+DT+tab",
    },
  },
  {
    title: "Zuraceff tab",
    description: "Cefixime Dispersible Tab IP 200 mg",
    brand: "Zuraceff",
    companyName: "ALKEM",
    packageSize: "10*10 Tab", 
    mrp: 109,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_zuraceff",
      url: "https://via.placeholder.com/150?text=Zuraceff+tab",
    },
  },
  {
    title: "Cefaclass-200 tab",
    description: "Cefixime Dispersible Tab IP 200 mg",
    brand: "Cefaclass-200",
    companyName: "MANKIND",
    packageSize: "10*10 Tab",
    mrp: 109,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_cefaclass-200",
      url: "https://via.placeholder.com/150?text=Cefaclass-200+tab",
    },
  },
  {
    title: "Ximeceff - 200 tab",
    description: "Cefixime Dispersible Tab IP 200 mg",
    brand: "Ximeceff",
    companyName: "LUPIN",
    packageSize: "10*10 Tab",
    mrp: 109,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_ximeceff-200",
      url: "https://via.placeholder.com/150?text=Ximeceff+-+200+tab",
    },
  },
  {
    title: "Numecet-Plus tab",
    description: "Nimesulide & Paracetamol tab",
    brand: "Numecet-Plus",
    companyName: "LEDERLE",
    packageSize: "Per strip", // Not exact, dummy
    mrp: 50,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_numecet-plus",
      url: "https://via.placeholder.com/150?text=Numecet-Plus+tab",
    },
  },
  {
    title: "Numecet-Plus Gold tab",
    description: "Nimesulide & Paracetamol tab",
    brand: "Numecet-Plus Gold",
    companyName: "LEDERLE",
    packageSize: "Per strip",
    mrp: 53,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_numecet-plus-gold",
      url: "https://via.placeholder.com/150?text=Numecet-Plus+Gold+tab",
    },
  },
  {
    title: "Bestoslide - P tab",
    description: "Nimesulide & Paracetamol tab",
    brand: "Bestoslide",
    companyName: "BESTO CHEM",
    packageSize: "Per strip",
    mrp: 102,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_bestoslide-p",
      url: "https://via.placeholder.com/150?text=Bestoslide+-+P+tab",
    },
  },
  {
    title: "Rabigen-DSR cap",
    description: "Rabeprazole Sodium(EC) & Domperidone(SR) cap",
    brand: "Rabigen-DSR",
    companyName: "BIOGEN",
    packageSize: "10*10 Tab", // Dummy
    mrp: 140,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_rabigen-dsr",
      url: "https://via.placeholder.com/150?text=Rabigen-DSR+cap",
    },
  },
  {
    title: "Robotac-DSR cap",
    description: "Rabeprazole Sodium(EC) & Domperidone(SR) cap",
    brand: "Robotac-DSR",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab", // Dummy
    mrp: 160,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_robotac-dsr",
      url: "https://via.placeholder.com/150?text=Robotac-DSR+cap",
    },
  },
  {
    title: "Daneeb-DSR cap",
    description: "Rabeprazole Sodium(EC) & Domperidone(SR) cap",
    brand: "Daneeb-DSR",
    companyName: "R.T PHARMA",
    packageSize: "10*10 Tab", // Dummy
    mrp: 125,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_daneeb-dsr",
      url: "https://via.placeholder.com/150?text=Daneeb-DSR+cap",
    },
  },
  {
    title: "Pantaled-DSR cap",
    description: "Pantoprazole Sodium Gastro-resistant & Domperidone Prolonged release cap",
    brand: "Pantaled-DSR",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab", // Dummy
    mrp: 145,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_pantaled-dsr",
      url: "https://via.placeholder.com/150?text=Pantaled-DSR+cap",
    },
  },
  {
    title: "Daneepan-DSR cap",
    description: "Pantoprazole Sodium Gastro-resistant & Domperidone cap",
    brand: "Daneepan-DSR",
    companyName: "R.T PHARMA",
    packageSize: "10*10 Tab", // Dummy
    mrp: 149,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_daneepan-dsr",
      url: "https://via.placeholder.com/150?text=Daneepan-DSR+cap",
    },
  },
  {
    title: "Acloled-P tab",
    description: "Aceclofenac + Paracetamol tab",
    brand: "Acloled-P",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 85,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_acloled-p",
      url: "https://via.placeholder.com/150?text=Acloled-P+tab",
    },
  },
  {
    title: "Acloled-SP tab",
    description: "Aceclofenac + Paracetamol + Serratioptidase tab",
    brand: "Acloled-SP",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 117,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_acloled-sp",
      url: "https://via.placeholder.com/150?text=Acloled-SP+tab",
    },
  },
  {
    title: "ALDIGESIC-SP",
    description: "Aceclofenac + Paracetamol + Serratioptidase",
    brand: "ALDIGESIC-SP",
    companyName: "ALKEM",
    packageSize: "10*10 Tab", // Dummy
    mrp: 120,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_aldigesic-sp",
      url: "https://via.placeholder.com/150?text=ALDIGESIC-SP",
    },
  },
  {
    title: "Voveled-Plus tab",
    description: "Diclofenac sodium & Paracetamol tab I.P",
    brand: "Voveled-Plus",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 40,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_voveled-plus",
      url: "https://via.placeholder.com/150?text=Voveled-Plus+tab",
    },
  },
  {
    title: "Vovimol tab",
    description: "Diclofenac sodium & Paracetamol tab I.P",
    brand: "Vovimol",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 44,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_vovimol",
      url: "https://via.placeholder.com/150?text=Vovimol+tab",
    },
  },
  {
    title: "Acloled-MR tab",
    description: "Aceclofenac, Paracetamol & Chlorzoxazone tab",
    brand: "Acloled-MR",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 100,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_acloled-mr",
      url: "https://via.placeholder.com/150?text=Acloled-MR+tab",
    },
  },
  {
    title: "Megaceclo-MR tab",
    description: "Aceclofenac, Paracetamol & Chlorzoxazone tab",
    brand: "Megaceclo-MR",
    companyName: "ARISTO",
    packageSize: "10*10 Tab",
    mrp: 125,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_megaceclo-mr",
      url: "https://via.placeholder.com/150?text=Megaceclo-MR+tab",
    },
  },
  {
    title: "Rabitap LS cap",
    description: "Rabeprazole Sodium(EC) & Levosulpiride(SR) cap",
    brand: "Rabitap LS",
    companyName: "ARISTO",
    packageSize: "10*10 Tab",
    mrp: 240,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_rabitap-ls",
      url: "https://via.placeholder.com/150?text=Rabitap+LS+cap",
    },
  },
  {
    title: "Zyrab LS cap",
    description: "Rabeprazole Sodium(EC) & Levosulpiride(SR) cap",
    brand: "Zyrab LS",
    companyName: "ZYDUS",
    packageSize: "10*10 Tab",
    mrp: 192,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_zyrab-ls",
      url: "https://via.placeholder.com/150?text=Zyrab+LS+cap",
    },
  },
  {
    title: "Aziled-500 tab",
    description: "Azithromycin 500 tab",
    brand: "Aziled-500",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 79,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_aziled-500",
      url: "https://via.placeholder.com/150?text=Aziled-500+tab",
    },
  },
  {
    title: "Azikem-500 tab",
    description: "Azithromycin 500 tab",
    brand: "Azikem-500",
    companyName: "ALKEM",
    packageSize: "10*10 Tab",
    mrp: 79,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_azikem-500",
      url: "https://via.placeholder.com/150?text=Azikem-500+tab",
    },
  },
  {
    title: "Azikem-250 tab",
    description: "Azithromycin 250 tab",
    brand: "Azikem-250",
    companyName: "ALKEM",
    packageSize: "10*10 Tab",
    mrp: 78,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_azikem-250",
      url: "https://via.placeholder.com/150?text=Azikem-250+tab",
    },
  },
  {
    title: "Zedloc-150 tab",
    description: "Ranitidine Tab 150 mg",
    brand: "Zedloc-150",
    companyName: "LEDERLE",
    packageSize: "10*30 Tab",
    mrp: 36,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_zedloc-150",
      url: "https://via.placeholder.com/150?text=Zedloc-150+tab",
    },
  },
  {
    title: "RASPAR 150 TAB",
    description: "Ranitidine Tab 150 mg",
    brand: "RASPAR",
    companyName: "AJANTA",
    packageSize: "20*3*10 Tab",
    mrp: 40,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_raspar-150",
      url: "https://via.placeholder.com/150?text=RASPAR+150+TAB",
    },
  },
  {
    title: "Moxday - 250 cap",
    description: "Amoxycillin Trihydrate cap I.P",
    brand: "Moxday - 250",
    companyName: "LEDERLE",
    packageSize: "10*10 Cap",
    mrp: 27,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_moxday-250",
      url: "https://via.placeholder.com/150?text=Moxday+-+250+cap",
    },
  },
  {
    title: "Labmox - 250 cap",
    description: "Amoxycillin Trihydrate cap I.P",
    brand: "Labmox - 250",
    companyName: "LABORATE",
    packageSize: "10*10 Cap",
    mrp: 27,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_labmox-250",
      url: "https://via.placeholder.com/150?text=Labmox+-+250+cap",
    },
  },
  {
    title: "HAEMOPROL XT tab",
    description: "Ferrous Ascorbate Folic Acid tab IP",
    brand: "HAEMOPROL XT",
    companyName: "ARISTO",
    packageSize: "10*10 Tab",
    mrp: 153,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_haemoprol-xt",
      url: "https://via.placeholder.com/150?text=HAEMOPROL+XT+tab",
    },
  },
  {
    title: "Oreled-XT tab",
    description: "Ferrous Ascorbate Folic Acid & Zinc tab",
    brand: "Oreled-XT",
    companyName: "LEDERLE",
    packageSize: "10*10 Tab",
    mrp: 185,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_oreled-xt",
      url: "https://via.placeholder.com/150?text=Oreled-XT+tab",
    },
  },
  {
    title: "OFLOLED OZ TAB",
    description: "Ofloxacin & Ornidazole tab I.P",
    brand: "OFLOLED OZ",
    companyName: "LEDERLE",
    packageSize: "20*10 Tab",
    mrp: 140,
    inStockNumber: 10,
    isAvailable: true,
    image: {
      public_id: "dummy_public_id_ofloed-oz",
      url: "https://via.placeholder.com/150?text=OFLOLED+OZ+TAB",
    },
  },
  // ... You can continue with other medicines similarly. Due to space limitation, please ask if you want to generate the full list programmatically.
];

export default medicines;
